# Flight Price Dataset EDA and Feature Engineering

In [1]:
#importing basic libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

c:\Users\soumi\AppData\Local\Programs\Python\Python312\Lib\site-packages\seaborn\_statistics.py:32: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 2.4.4)
  from scipy.stats import gaussian_kde

In [84]:
df = pd.read_excel('flight_price.xlsx')

In [85]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [86]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [87]:
df.drop(['Route'], axis=1, inplace=True)

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
dtypes: int64(1), object(9)
memory usage: 834.7+ KB

In [89]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [90]:
df[df['Total_Stops'].isnull()]

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,09:45,09:25 07 May,23h 40m,NaN,No info,7480

## Feature Engineering

In [91]:
df['Total_Stops'].unique(), '-------------------' , df['Total_Stops'].mode()

(array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
       dtype=object),
 '-------------------',
 0    1 stop
 Name: Total_Stops, dtype: object)

In [92]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0, '1 stop': 1, '2 stops': 2, '3 stops': 3, '4 stops': 4, np.nan : 1})
df['Total_Stops']

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10683, dtype: int64

In [93]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1,No info,13302

In [94]:
# Date of journey
df['date'] = df['Date_of_Journey'].str.split('/').str[0].astype(int)
df['month'] = df['Date_of_Journey'].str.split('/').str[1].astype(int)
df['year'] = df['Date_of_Journey'].str.split('/').str[2].astype(int)

df.head()

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2,No info,7662,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2,No info,13882,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1,No info,6218,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1,No info,13302,1,3,2019

In [95]:
df.drop('Date_of_Journey', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Dep_Time         10683 non-null  object
 4   Arrival_Time     10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10683 non-null  int64
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   date             10683 non-null  int64
 10  month            10683 non-null  int64
 11  year             10683 non-null  int64
dtypes: int64(5), object(7)
memory usage: 1001.7+ KB

In [96]:
# duration
df['duration_hours'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['duration_hours'].value_counts()

duration_hours
2     2402
1      621
3      501
7      487
5      481
9      445
12     428
8      424
13     407
11     365
10     355
6      340
14     337
15     268
23     265
26     241
16     234
4      222
22     218
24     197
21     196
25     186
27     179
20     162
18     141
19     134
17     129
28      94
29      65
30      49
38      34
37      17
33      13
32       9
34       8
35       7
36       7
31       6
47       2
42       2
39       2
5m       1
41       1
40       1
Name: count, dtype: int64

In [99]:
df.loc[df['duration_hours'] == '5m', 'duration_hours'] = 0
df['duration_hours'] = df['duration_hours'].astype(int)

In [100]:
df['duration_mins'] = df['Duration'].str.split(' ').str[1].str.split('m').str[0]
df['duration_mins'] = df['duration_mins'].fillna(0)

df['duration_mins'] = df['duration_mins'].astype(int)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Dep_Time         10683 non-null  object
 4   Arrival_Time     10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10683 non-null  int64
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   date             10683 non-null  int64
 10  month            10683 non-null  int64
 11  year             10683 non-null  int64
 12  duration_hours   10683 non-null  int64
 13  duration_mins    10683 non-null  int64
dtypes: int64(7), object(7)
memory usage: 1.1+ MB

In [102]:
df.head()

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,duration_hours,duration_mins
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0,No info,3897,24,3,2019,2,50
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2,No info,7662,1,5,2019,7,25
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,19h,2,No info,13882,9,6,2019,19,0
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1,No info,6218,12,5,2019,5,25
4,IndiGo,Banglore,New Delhi,16:50,21:35,4h 45m,1,No info,13302,1,3,2019,4,45

In [103]:
df['total_duration'] = df['duration_hours'] + df['duration_mins']/60
df.head(3)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,duration_hours,duration_mins,total_duration
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0,No info,3897,24,3,2019,2,50,2.833333
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2,No info,7662,1,5,2019,7,25,7.416667
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,19h,2,No info,13882,9,6,2019,19,0,19.000000

In [104]:
df.drop(['duration_hours', 'duration_mins', 'Duration'], axis=1, inplace=True)

In [105]:
df

,Airline,Source,Destination,Dep_Time,Arrival_Time,Total_Stops,Additional_Info,Price,date,month,year,total_duration
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,0,No info,3897,24,3,2019,2.833333
1,Air India,Kolkata,Banglore,05:50,13:15,2,No info,7662,1,5,2019,7.416667
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,2,No info,13882,9,6,2019,19.000000
3,IndiGo,Kolkata,Banglore,18:05,23:30,1,No info,6218,12,5,2019,5.416667
4,IndiGo,Banglore,New Delhi,16:50,21:35,1,No info,13302,1,3,2019,4.750000
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,19:55,22:25,0,No info,4107,9,4,2019,2.500000
10679,Air India,Kolkata,Banglore,20:45,23:20,0,No info,4145,27,4,2019,2.583333
10680,Jet Airways,Banglore,Delhi,08:20,11:20,0,No info,7229,27,4,2019,3.000000
10681,Vistara,Banglore,New Delhi,11:30,14:10,0,No info,12648,1,3,2019,2.666667
10682,Air India,Delhi,Cochin,10:55,19:15,2,No info,11753,9,5,2019,8.333333

In [106]:
# Departure Time
df['Dep_hour'] = df['Dep_Time'].str.split(':').str[0]
df['Dep_min'] = df['Dep_Time'].str.split(':').str[1]

In [108]:
df['Dep_hour'] = df.Dep_hour.astype(int)
df['Dep_min'] = df.Dep_min.astype(int)

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Dep_Time         10683 non-null  object
 4   Arrival_Time     10683 non-null  object
 5   Total_Stops      10683 non-null  int64
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   date             10683 non-null  int64
 9   month            10683 non-null  int64
 10  year             10683 non-null  int64
 11  total_duration   10683 non-null  float64
 12  Dep_hour         10683 non-null  int64
 13  Dep_min          10683 non-null  int64
dtypes: float64(1), int64(7), object(6)
memory usage: 1.1+ MB

In [110]:
df.drop(['Dep_Time'], inplace=True, axis=1)

In [111]:
# arrival time
df.head()

,Airline,Source,Destination,Arrival_Time,Total_Stops,Additional_Info,Price,date,month,year,total_duration,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,01:10 22 Mar,0,No info,3897,24,3,2019,2.833333,22,20
1,Air India,Kolkata,Banglore,13:15,2,No info,7662,1,5,2019,7.416667,5,50
2,Jet Airways,Delhi,Cochin,04:25 10 Jun,2,No info,13882,9,6,2019,19.000000,9,25
3,IndiGo,Kolkata,Banglore,23:30,1,No info,6218,12,5,2019,5.416667,18,5
4,IndiGo,Banglore,New Delhi,21:35,1,No info,13302,1,3,2019,4.750000,16,50

In [113]:
df['arrival_hour'] = df['Arrival_Time'].str.split(' ').str[0].str.split(':').str[0].astype(int)
df['arrival_min'] = df['Arrival_Time'].str.split(' ').str[0].str.split(':').str[1].astype(int)

In [114]:
df.drop(['Arrival_Time'], inplace=True, axis=1)
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,date,month,year,total_duration,Dep_hour,Dep_min,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,2.833333,22,20,1,10
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,7.416667,5,50,13,15
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,19.000000,9,25,4,25
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,5.416667,18,5,23,30
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,4.750000,16,50,21,35

In [116]:
# categorical features
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

df2 = pd.DataFrame(encoder.fit_transform(df[['Airline', 'Source', 'Destination']]).toarray(), 
                   columns=encoder.get_feature_names_out())

df2

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [119]:
df_ready = pd.concat([df, df2], axis=1)
df_ready.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,date,month,year,total_duration,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,2.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,7.416667,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,19.000000,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,5.416667,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,4.750000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [120]:
df_ready.drop(['Airline', 'Source','Destination'], axis=1, inplace=True)

In [121]:
df.Additional_Info.value_counts()

Additional_Info
No info                         8345
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [122]:
df_ready.drop(['Additional_Info'], axis=1, inplace=True)

In [124]:
cols = [col for col in df_ready.columns if col != 'Price'] + ['Price']
df_ready = df_ready[cols]

In [125]:
df_ready.head(10)

,Total_Stops,date,month,year,total_duration,Dep_hour,Dep_min,arrival_hour,arrival_min,Airline_Air Asia,...,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Price
0,0,24,3,2019,2.833333,22,20,1,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3897
1,2,1,5,2019,7.416667,5,50,13,15,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,7662
2,2,9,6,2019,19.000000,9,25,4,25,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13882
3,1,12,5,2019,5.416667,18,5,23,30,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,6218
4,1,1,3,2019,4.750000,16,50,21,35,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,13302
5,0,24,6,2019,2.416667,9,0,11,25,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3873
6,1,12,3,2019,15.500000,18,55,10,25,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11087
7,1,1,3,2019,21.083333,8,0,5,5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,22270
8,1,12,3,2019,25.500000,8,55,10,25,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11087
9,1,27,5,2019,7.833333,11,25,19,15,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,8625