# Data Encoding

### one hot encoding

In [22]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [23]:
df = pd.DataFrame({
    'color' : ['red', 'green', 'blue', 'green', 'green', 'red']
})
df

   color
0    red
1  green
2   blue
3  green
4  green
5    red

In [24]:
# create and instance of OHE
encoder = OneHotEncoder()

In [25]:
# perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [26]:
type(df[['color']])

pandas.core.frame.DataFrame

In [27]:
type(df['color'])

pandas.core.series.Series

In [28]:
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          1.0        0.0
5         0.0          0.0        1.0

In [29]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0
3  green         0.0          1.0        0.0
4  green         0.0          1.0        0.0
5    red         0.0          0.0        1.0

In [30]:
import seaborn as sns
tips = sns.load_dataset('tips')

In [31]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [36]:
print(tips['sex'].value_counts(), "\n")
print(tips['smoker'].value_counts(), "\n")
print(tips['day'].value_counts(), "\n")
print(tips['time'].value_counts(), "\n")

sex
Male      157
Female     87
Name: count, dtype: int64

smoker
No     151
Yes     93
Name: count, dtype: int64

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [40]:
encoder_gender = OneHotEncoder()
encoded_gender = encoder_gender.fit_transform(tips[['sex']]).toarray()

In [41]:
encoder_smoker = OneHotEncoder()
encoded_smoker = encoder_smoker.fit_transform(tips[['smoker']]).toarray()

In [42]:
encoder_day = OneHotEncoder()
encoded_day = encoder_day.fit_transform(tips[['day']]).toarray()

In [44]:
encoder_time = OneHotEncoder()
encoded_time = encoder_time.fit_transform(tips[['time']]).toarray()

In [46]:
# tips_encoded = pd.DataFrame({
#     encoded_gender,
#     encoded_smoker,
#     encoded_day,
#     encoded_time
# }, columns=[
#     encoder_gender.get_feature_names_out(),
#     encoder_smoker.get_feature_names_out(),
#     encoder_day.get_feature_names_out(),
#     encoder_time.get_feature_names_out(),
# ]) wrong method

import numpy as np

tips_encoded = pd.DataFrame(
    np.hstack([
        encoded_gender,
        encoded_smoker,
        encoded_day,
        encoded_time
    ]),
    columns=np.concatenate([
        encoder_gender.get_feature_names_out(),
        encoder_smoker.get_feature_names_out(),
        encoder_day.get_feature_names_out(),
        encoder_time.get_feature_names_out()
    ])
)

tips_encoded.head()

   sex_Female  sex_Male  smoker_No  ...  day_Thur  time_Dinner  time_Lunch
0         1.0       0.0        1.0  ...       0.0          1.0         0.0
1         0.0       1.0        1.0  ...       0.0          1.0         0.0
2         0.0       1.0        1.0  ...       0.0          1.0         0.0
3         0.0       1.0        1.0  ...       0.0          1.0         0.0
4         1.0       0.0        1.0  ...       0.0          1.0         0.0

[5 rows x 10 columns]

In [47]:
# best approach - encode all features in one go

encoder = OneHotEncoder(sparse_output=False)
categorical_cols = ['sex', 'smoker', 'day', 'time']

In [48]:
encoded = encoder.fit_transform(tips[categorical_cols])

In [50]:
tips_encoded_better = pd.DataFrame(encoded,
                                columns=encoder.get_feature_names_out(categorical_cols))

tips_encoded_better.head(10)

   sex_Female  sex_Male  smoker_No  ...  day_Thur  time_Dinner  time_Lunch
0         1.0       0.0        1.0  ...       0.0          1.0         0.0
1         0.0       1.0        1.0  ...       0.0          1.0         0.0
2         0.0       1.0        1.0  ...       0.0          1.0         0.0
3         0.0       1.0        1.0  ...       0.0          1.0         0.0
4         1.0       0.0        1.0  ...       0.0          1.0         0.0
5         0.0       1.0        1.0  ...       0.0          1.0         0.0
6         0.0       1.0        1.0  ...       0.0          1.0         0.0
7         0.0       1.0        1.0  ...       0.0          1.0         0.0
8         0.0       1.0        1.0  ...       0.0          1.0         0.0
9         0.0       1.0        1.0  ...       0.0          1.0         0.0

[10 rows x 10 columns]

In [60]:
whole_tips = pd.concat([tips[['total_bill', 'tip']],tips_encoded_better, tips['size']], axis=1)
whole_tips

     total_bill   tip  sex_Female  ...  time_Dinner  time_Lunch  size
0         16.99  1.01         1.0  ...          1.0         0.0     2
1         10.34  1.66         0.0  ...          1.0         0.0     3
2         21.01  3.50         0.0  ...          1.0         0.0     3
3         23.68  3.31         0.0  ...          1.0         0.0     2
4         24.59  3.61         1.0  ...          1.0         0.0     4
..          ...   ...         ...  ...          ...         ...   ...
239       29.03  5.92         0.0  ...          1.0         0.0     3
240       27.18  2.00         1.0  ...          1.0         0.0     2
241       22.67  2.00         0.0  ...          1.0         0.0     2
242       17.82  1.75         0.0  ...          1.0         0.0     2
243       18.78  3.00         1.0  ...          1.0         0.0     2

[244 rows x 13 columns]

### Label encoding

In [53]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [54]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\soumi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 1, 1, 2])

In [57]:
lbl_encoder.transform([['red']])

c:\Users\soumi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

### Ordinal encoding

In [61]:
from sklearn.preprocessing import OrdinalEncoder

In [62]:
df2 = pd.DataFrame({
    'size' : ['small', 'big', 'med', 'small', 'med', 'small']
})
df2

    size
0  small
1    big
2    med
3  small
4    med
5  small

In [64]:
## create and instance of ordinal encoder and then fit transform
encoder = OrdinalEncoder(categories=[['small', 'med', 'big']])

In [66]:
encoder.fit_transform(df2[['size']])

array([[0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.]])

In [67]:
encoder.transform([['small']])

c:\Users\soumi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])