# handling imabalanced data

### Generating data and setting up

In [1]:
import pandas as pd
import numpy as np

In [6]:
np.random.seed(42)
n = 1000
class_ratio = 0.9

n_class_0 = int(n*class_ratio)
n_class_1 = int(n-n_class_0)

n_class_0,n_class_1

(900, 100)

In [9]:
# Creating dataset

class0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : np.zeros(dtype=int, shape=(n_class_0))
})

print(class0.head())

class1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target' : np.ones(dtype=int, shape=(n_class_1))
})

class1.head()

   feature_1  feature_2  target
0  -1.388543  -0.992866       0
1  -1.600271  -1.445205       0
2  -1.217283   0.666270       0
3   0.159463   0.577979       0
4  -0.892788   0.577364       0

   feature_1  feature_2  target
0  -0.188202  -0.025494       1
1  -0.103587  -0.217159       1
2  -0.213875   0.058370       1
3   0.970316  -0.603859       1
4   0.418760  -0.343206       1

In [12]:
class0.target.size, class1.target.size

(900, 100)

In [20]:
df = pd.concat([class0, class1]).reset_index(drop=True)
display(df.head()), display(df.tail())

   feature_1  feature_2  target
0  -1.388543  -0.992866       0
1  -1.600271  -1.445205       0
2  -1.217283   0.666270       0
3   0.159463   0.577979       0
4  -0.892788   0.577364       0

     feature_1  feature_2  target
995   0.523961  -0.106194       1
996  -0.399900   3.098299       1
997  -0.745168  -0.258175       1
998  -0.104968   0.510124       1
999   0.612791  -0.649365       1

(None, None)

In [21]:
df_minority = df[df['target'] == 1]
df_minority

     feature_1  feature_2  target
900  -0.188202  -0.025494       1
901  -0.103587  -0.217159       1
902  -0.213875   0.058370       1
903   0.970316  -0.603859       1
904   0.418760  -0.343206       1
..         ...        ...     ...
995   0.523961  -0.106194       1
996  -0.399900   3.098299       1
997  -0.745168  -0.258175       1
998  -0.104968   0.510124       1
999   0.612791  -0.649365       1

[100 rows x 3 columns]

In [22]:
df_majority = df[df['target'] == 0]
df_majority

     feature_1  feature_2  target
0    -1.388543  -0.992866       0
1    -1.600271  -1.445205       0
2    -1.217283   0.666270       0
3     0.159463   0.577979       0
4    -0.892788   0.577364       0
..         ...        ...     ...
895  -0.198196  -1.742772       0
896   0.510157   0.409439       0
897   1.272570  -0.276672       0
898   0.126314   0.113394       0
899  -0.469131   0.458994       0

[900 rows x 3 columns]

In [24]:
len(df_majority)

900

### Upscaling - increasing the minority

In [23]:
from sklearn.utils import resample

In [26]:
minorty_upscaled = resample(df_minority, replace=True, n_samples=len(df_majority))
minorty_upscaled.target.size

900

In [28]:
df_upscaled = pd.concat([df_majority, minorty_upscaled]).reset_index(drop=True)
df_upscaled

      feature_1  feature_2  target
0     -1.388543  -0.992866       0
1     -1.600271  -1.445205       0
2     -1.217283   0.666270       0
3      0.159463   0.577979       0
4     -0.892788   0.577364       0
...         ...        ...     ...
1795   0.359739   0.029191       1
1796   1.711029  -0.284837       1
1797   1.128240  -1.355970       1
1798  -0.498634   0.697974       1
1799   2.824331  -0.836092       1

[1800 rows x 3 columns]

### Downsampling - reducing the majority

In [30]:
majority_downsampled = resample(df_majority,
                                replace=False,
                                n_samples=len(df_minority))
majority_downsampled.target.size

100

In [32]:
df_downsampled = pd.concat([majority_downsampled, df_minority]).reset_index(drop=True)
df_downsampled

     feature_1  feature_2  target
0    -0.525631   1.092107       0
1    -0.397558   0.957840       0
2     0.508608  -0.635410       0
3    -2.630730   1.071081       0
4     0.004230   0.383168       0
..         ...        ...     ...
195   0.523961  -0.106194       1
196  -0.399900   3.098299       1
197  -0.745168  -0.258175       1
198  -0.104968   0.510124       1
199   0.612791  -0.649365       1

[200 rows x 3 columns]