## Task 1: Student Marks Analyzer

In [1]:
import numpy as np
import pandas as pd

In [10]:
df = pd.DataFrame({
    "name" : ["rahul", "sanya", "sanyam", "abhinav", "soumil", "dhruv", "chakshu", "aditya","disha", "yashika"],
    "maths" : np.random.randint(1, 100, size=(10)),
    "science" : np.random.randint(1, 100, size=(10)),
    "English" : np.random.randint(1, 100, size=(10)),
    }, index=range(1,11))

df

       name  maths  science  English
1     rahul     95       26       75
2     sanya     98       54       83
3    sanyam     98       49       53
4   abhinav     64       81        4
5    soumil     47       57       53
6     dhruv     64       46       10
7   chakshu     25       91       65
8    aditya     33       14       13
9     disha     84       12       93
10  yashika     83       94       14

- Calculate average marks per student
- Find topper
- Find subject-wise average
- Add a “Pass/Fail” column

In [36]:
avg_marks = np.round(df.iloc[:,1:4].sum(axis=1)/3, decimals=2)
avg_marks

1     65.33
2     78.33
3     66.67
4     49.67
5     52.33
6     40.00
7     60.33
8     20.00
9     63.00
10    63.67
dtype: float64

In [37]:
df["avg_marks"] = avg_marks
df

       name  maths  science  English  avg_marks
1     rahul     95       26       75      65.33
2     sanya     98       54       83      78.33
3    sanyam     98       49       53      66.67
4   abhinav     64       81        4      49.67
5    soumil     47       57       53      52.33
6     dhruv     64       46       10      40.00
7   chakshu     25       91       65      60.33
8    aditya     33       14       13      20.00
9     disha     84       12       93      63.00
10  yashika     83       94       14      63.67

In [38]:
topper = df.avg_marks.idxmax()
df.loc[topper]

name         sanya
maths           98
science         54
English         83
avg_marks    78.33
Name: 2, dtype: object

In [39]:
subject_wise_avg = df.loc[:, ['maths', 'science', 'English']].sum()/10
subject_wise_avg

maths      69.1
science    52.4
English    46.3
dtype: float64

In [49]:
df["result"] = df[["maths", "science", "English"]].apply(lambda row : "pass" if (row > 40).all() else "fail", axis=1)

In [50]:
df

       name  maths  science  English  avg_marks result
1     rahul     95       26       75      65.33   fail
2     sanya     98       54       83      78.33   pass
3    sanyam     98       49       53      66.67   pass
4   abhinav     64       81        4      49.67   fail
5    soumil     47       57       53      52.33   pass
6     dhruv     64       46       10      40.00   fail
7   chakshu     25       91       65      60.33   fail
8    aditya     33       14       13      20.00   fail
9     disha     84       12       93      63.00   fail
10  yashika     83       94       14      63.67   fail

## step 2 - numpy core foundation
- Find row-wise sum
- Find column-wise max
- Replace all values > 50 with 0
- Normalize array (0–1 scaling)

In [24]:
import numpy as np
arr = np.random.randint(1,100, size=(5,5))
arr

array([[53, 25, 92, 45, 49],
       [66, 59, 14, 55, 18],
       [99, 63, 25, 87, 10],
       [96, 50,  4, 84,  5],
       [16, 91, 85, 16, 52]], dtype=int32)

In [18]:
row_sum = arr.sum(axis=1)
row_sum

array([167, 320, 210, 204,  96])

In [19]:
col_max = arr.max(axis=0)
col_max

array([92, 73, 59, 86, 92], dtype=int32)

In [25]:
arr2 = arr
arr2[arr2 > 50] = 0
arr2

array([[ 0, 25,  0, 45, 49],
       [ 0,  0, 14,  0, 18],
       [ 0,  0, 25,  0, 10],
       [ 0, 50,  4,  0,  5],
       [16,  0,  0, 16,  0]], dtype=int32)

In [26]:
arr = (arr - arr.min())/ (arr.max() - arr.min())
arr

array([[0.  , 0.5 , 0.  , 0.9 , 0.98],
       [0.  , 0.  , 0.28, 0.  , 0.36],
       [0.  , 0.  , 0.5 , 0.  , 0.2 ],
       [0.  , 1.  , 0.08, 0.  , 0.1 ],
       [0.32, 0.  , 0.  , 0.32, 0.  ]])