In [54]:
import numpy as np
import pandas as pd

## Messy Dataset Cleaning

In [55]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["samaira", "sanya", "sanyam", "abhinav", "soumil", 
             "dhruv", "chakshu", "aditya", "disha", "yashika"],
    
    "maths": [85, "90", 78, np.nan, "65", 85, "absent", 92, 88, 90],
    
    "science": [88, 76, "80", 70, np.nan, 88, 91, "85", 89, 76],
    
    "english": [90, 85, 88, "92", 75, np.nan, 84, 90, "eighty", 85]
})

# Add duplicate rows
df = pd.concat([df, df.iloc[[2, 5]]], ignore_index=True)

subjects = ['maths', 'science', 'english']
df

       name   maths science english
0   samaira      85      88      90
1     sanya      90      76      85
2    sanyam      78      80      88
3   abhinav     NaN      70      92
4    soumil      65     NaN      75
5     dhruv      85      88     NaN
6   chakshu  absent      91      84
7    aditya      92      85      90
8     disha      88      89  eighty
9   yashika      90      76      85
10   sanyam      78      80      88
11    dhruv      85      88     NaN

In [56]:
df[df.isna().any(axis=1)]

       name maths science english
3   abhinav   NaN      70      92
4    soumil    65     NaN      75
5     dhruv    85      88     NaN
11    dhruv    85      88     NaN

In [57]:
df.isna().sum(axis=1)

0     0
1     0
2     0
3     1
4     1
5     1
6     0
7     0
8     0
9     0
10    0
11    1
dtype: int64

In [58]:
df.fillna(0)

       name   maths science english
0   samaira      85      88      90
1     sanya      90      76      85
2    sanyam      78      80      88
3   abhinav       0      70      92
4    soumil      65       0      75
5     dhruv      85      88       0
6   chakshu  absent      91      84
7    aditya      92      85      90
8     disha      88      89  eighty
9   yashika      90      76      85
10   sanyam      78      80      88
11    dhruv      85      88       0

In [62]:
df_clean = df[subjects].apply(pd.to_numeric, errors = "coerce")
df[subjects] = df_clean
df.fillna(0, inplace=True)
df

      name  maths  science  english
0  samaira   85.0     88.0     90.0
1    sanya   90.0     76.0     85.0
2   sanyam   78.0     80.0     88.0
3  abhinav    0.0     70.0     92.0
4   soumil   65.0      0.0     75.0
5    dhruv   85.0     88.0      0.0
6  chakshu    0.0     91.0     84.0
7   aditya   92.0     85.0     90.0
8    disha   88.0     89.0      0.0
9  yashika   90.0     76.0     85.0

In [63]:
df.drop_duplicates(inplace=True)
df

      name  maths  science  english
0  samaira   85.0     88.0     90.0
1    sanya   90.0     76.0     85.0
2   sanyam   78.0     80.0     88.0
3  abhinav    0.0     70.0     92.0
4   soumil   65.0      0.0     75.0
5    dhruv   85.0     88.0      0.0
6  chakshu    0.0     91.0     84.0
7   aditya   92.0     85.0     90.0
8    disha   88.0     89.0      0.0
9  yashika   90.0     76.0     85.0

In [64]:
df.rename(columns={
    "maths" : "Mathematics",
    "science" : "Physics",
    "english" : "eng",
}, inplace=True)
df

      name  Mathematics  Physics   eng
0  samaira         85.0     88.0  90.0
1    sanya         90.0     76.0  85.0
2   sanyam         78.0     80.0  88.0
3  abhinav          0.0     70.0  92.0
4   soumil         65.0      0.0  75.0
5    dhruv         85.0     88.0   0.0
6  chakshu          0.0     91.0  84.0
7   aditya         92.0     85.0  90.0
8    disha         88.0     89.0   0.0
9  yashika         90.0     76.0  85.0