In [26]:
import numpy as np
import pandas as pd

In [27]:
arr = np.random.randint(1,50,size=(10,3))
arr

array([[46, 11, 43],
       [41, 15, 20],
       [ 9, 45, 15],
       [43,  7, 45],
       [22, 24,  6],
       [40, 37, 33],
       [15, 43, 41],
       [12, 21, 19],
       [46, 14, 35],
       [40, 48, 10]], dtype=int32)

In [28]:
df = pd.DataFrame(arr, columns=['apple','ball','cat'])
df

   apple  ball  cat
0     46    11   43
1     41    15   20
2      9    45   15
3     43     7   45
4     22    24    6
5     40    37   33
6     15    43   41
7     12    21   19
8     46    14   35
9     40    48   10

In [29]:
df.mean(axis=1)

0    33.333333
1    25.333333
2    23.000000
3    31.666667
4    17.333333
5    36.666667
6    33.000000
7    17.333333
8    31.666667
9    32.666667
dtype: float64

In [35]:
tmean = np.round(np.mean(df))
tmean

np.float64(30.0)

In [36]:
df[df < 10] = tmean
df

   apple  ball  cat
0     46    11   43
1     41    15   20
2     28    45   15
3     43    28   45
4     22    24   28
5     40    37   33
6     15    43   41
7     12    21   19
8     46    14   35
9     40    48   10

In [37]:
df.mean().mean()

np.float64(30.266666666666666)

In [61]:
marks = pd.DataFrame({
    "name" : ["samaira", "sanya", "sanyam", "abhinav", "soumil", "dhruv", "chakshu", "aditya","disha", "yashika"],
    "maths" : np.random.randint(50, 100, size=(10)),
    "science" : np.random.randint(50, 100, size=(10)),
    "english" : np.random.randint(50, 100, size=(10)),
    }, index=range(1,11))
marks

       name  maths  science  english
1   samaira     80       65       90
2     sanya     79       82       95
3    sanyam     66       65       61
4   abhinav     84       61       65
5    soumil     93       53       81
6     dhruv     83       95       90
7   chakshu     86       54       89
8    aditya     79       73       58
9     disha     91       82       55
10  yashika     65       79       87

In [55]:
marks[marks[["maths", "science", "english"]] < 60] = "fail"
marks

C:\Users\soumi\AppData\Local\Temp\ipykernel_35976\323189905.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'fail' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  marks[marks[["maths", "science", "english"]] < 60] = "fail"

       name maths science english
1   samaira    81    fail      68
2     sanya  fail    fail      72
3    sanyam    76      93      86
4   abhinav    97      80    fail
5    soumil    78      73    fail
6     dhruv    85      88    fail
7   chakshu    91      86      86
8    aditya    63      88      74
9     disha    84    fail      89
10  yashika    63      97      90

In [59]:
flat = arr.ravel()
np.max(flat[flat != np.max(flat)])

np.int32(46)

In [87]:
marks["average"] = np.round(marks.iloc[:, 1:4].mean(axis=1))
avg = marks.average.mean()
(marks.average > avg).sum()

marks

       name  maths  science  english  average
1   samaira     80       65       90     78.0
2     sanya     79       82       95     85.0
3    sanyam     66       65       61     64.0
4   abhinav     84       61       65     70.0
5    soumil     93       53       81     76.0
6     dhruv     83       95       90     89.0
7   chakshu     86       54       89     76.0
8    aditya     79       73       58     70.0
9     disha     91       82       55     76.0
10  yashika     65       79       87     77.0

In [91]:
marks.loc[11] = ['yashika', 10, 99, 99, 80]
marks

       name  maths  science  english  average
1   samaira     80       65       90     78.0
2     sanya     79       82       95     85.0
3    sanyam     66       65       61     64.0
4   abhinav     84       61       65     70.0
5    soumil     93       53       81     76.0
6     dhruv     83       95       90     89.0
7   chakshu     86       54       89     76.0
8    aditya     79       73       58     70.0
9     disha     91       82       55     76.0
10    ayush     10       99       99     80.0
11  yashika     10       99       99     80.0

In [ ]:
fullmarks = marks[["maths", "science", "english"]].apply(lambda row: row == 99, axis = 1)
fullmarks

   name  maths  science  english  average
1   NaN    NaN      NaN      NaN      NaN
2   NaN    NaN      NaN      NaN      NaN
3   NaN    NaN      NaN      NaN      NaN
4   NaN    NaN      NaN      NaN      NaN
5   NaN    NaN      NaN      NaN      NaN
6   NaN    NaN      NaN      NaN      NaN
7   NaN    NaN      NaN      NaN      NaN
8   NaN    NaN      NaN      NaN      NaN
9   NaN    NaN      NaN      NaN      NaN
10  NaN    NaN     99.0     99.0      NaN
11  NaN    NaN     99.0     99.0      NaN

In [107]:
marks.loc[(marks[["maths", "science", "english"]] == 99).any(axis=1), 'name']

10      ayush
11    yashika
Name: name, dtype: object

In [106]:
(marks[["maths","science","english"]] == 100)

    maths  science  english
1   False    False    False
2   False    False    False
3   False    False    False
4   False    False    False
5   False    False    False
6   False    False    False
7   False    False    False
8   False    False    False
9   False    False    False
10  False    False    False
11  False    False    False

In [115]:
marks.loc[(marks['average'].argmax() + 1)]
# marks

name       dhruv
maths         83
science       95
english       90
average     89.0
Name: 6, dtype: object