In [77]:
import numpy as np
import pandas as pd

In [78]:
df = pd.DataFrame({
    "name" : ["samaira", "sanya", "sanyam", "abhinav", "soumil", "dhruv", "chakshu", "aditya","disha", "yashika"],
    "maths" : np.random.randint(50, 100, size=(10)),
    "science" : np.random.randint(50, 100, size=(10)),
    "english" : np.random.randint(50, 100, size=(10)),
    }, index=range(1,11))

df

       name  maths  science  english
1   samaira     93       87       73
2     sanya     83       86       61
3    sanyam     53       78       82
4   abhinav     58       65       83
5    soumil     56       80       90
6     dhruv     57       52       98
7   chakshu     98       89       95
8    aditya     65       58       70
9     disha     92       85       92
10  yashika     69       55       62

In [79]:
df['total marks'] = df[["maths", "science", "english"]].sum(axis = 1)
df

       name  maths  science  english  total marks
1   samaira     93       87       73          253
2     sanya     83       86       61          230
3    sanyam     53       78       82          213
4   abhinav     58       65       83          206
5    soumil     56       80       90          226
6     dhruv     57       52       98          207
7   chakshu     98       89       95          282
8    aditya     65       58       70          193
9     disha     92       85       92          269
10  yashika     69       55       62          186

In [80]:
df['percentage'] = np.round(df['total marks']/3, 2)
df

       name  maths  science  english  total marks  percentage
1   samaira     93       87       73          253       84.33
2     sanya     83       86       61          230       76.67
3    sanyam     53       78       82          213       71.00
4   abhinav     58       65       83          206       68.67
5    soumil     56       80       90          226       75.33
6     dhruv     57       52       98          207       69.00
7   chakshu     98       89       95          282       94.00
8    aditya     65       58       70          193       64.33
9     disha     92       85       92          269       89.67
10  yashika     69       55       62          186       62.00

In [81]:
maths_topper = df[df.maths > 80]
maths_topper

      name  maths  science  english  total marks  percentage
1  samaira     93       87       73          253       84.33
2    sanya     83       86       61          230       76.67
7  chakshu     98       89       95          282       94.00
9    disha     92       85       92          269       89.67

In [82]:
fails = df[df[["maths", "science", "english"]].apply(lambda row: (row < 60).any(), axis=1)]
fails

       name  maths  science  english  total marks  percentage
3    sanyam     53       78       82          213       71.00
4   abhinav     58       65       83          206       68.67
5    soumil     56       80       90          226       75.33
6     dhruv     57       52       98          207       69.00
8    aditya     65       58       70          193       64.33
10  yashika     69       55       62          186       62.00

In [83]:
good_all =  df[df[["maths", "science", "english"]].apply(lambda row: (row > 70).all(), axis=1)]
good_all

      name  maths  science  english  total marks  percentage
1  samaira     93       87       73          253       84.33
7  chakshu     98       89       95          282       94.00
9    disha     92       85       92          269       89.67

In [84]:
df_sorted_maths = df.sort_values("maths", ascending=False)
df_sorted_maths

       name  maths  science  english  total marks  percentage
7   chakshu     98       89       95          282       94.00
1   samaira     93       87       73          253       84.33
9     disha     92       85       92          269       89.67
2     sanya     83       86       61          230       76.67
10  yashika     69       55       62          186       62.00
8    aditya     65       58       70          193       64.33
4   abhinav     58       65       83          206       68.67
6     dhruv     57       52       98          207       69.00
5    soumil     56       80       90          226       75.33
3    sanyam     53       78       82          213       71.00

In [85]:
df_sorted_avg = df.sort_values("total marks", ascending=False)
df_sorted_avg

       name  maths  science  english  total marks  percentage
7   chakshu     98       89       95          282       94.00
9     disha     92       85       92          269       89.67
1   samaira     93       87       73          253       84.33
2     sanya     83       86       61          230       76.67
5    soumil     56       80       90          226       75.33
3    sanyam     53       78       82          213       71.00
6     dhruv     57       52       98          207       69.00
4   abhinav     58       65       83          206       68.67
8    aditya     65       58       70          193       64.33
10  yashika     69       55       62          186       62.00

In [86]:
df_sorted_avg[:3]

      name  maths  science  english  total marks  percentage
7  chakshu     98       89       95          282       94.00
9    disha     92       85       92          269       89.67
1  samaira     93       87       73          253       84.33

In [87]:
df = df.rename(columns={"maths":"Maths"})

In [88]:
df2 = df.drop(columns=["english"])
df2

       name  Maths  science  total marks  percentage
1   samaira     93       87          253       84.33
2     sanya     83       86          230       76.67
3    sanyam     53       78          213       71.00
4   abhinav     58       65          206       68.67
5    soumil     56       80          226       75.33
6     dhruv     57       52          207       69.00
7   chakshu     98       89          282       94.00
8    aditya     65       58          193       64.33
9     disha     92       85          269       89.67
10  yashika     69       55          186       62.00

In [89]:
df2 = df.drop(index=2)
df2

       name  Maths  science  english  total marks  percentage
1   samaira     93       87       73          253       84.33
3    sanyam     53       78       82          213       71.00
4   abhinav     58       65       83          206       68.67
5    soumil     56       80       90          226       75.33
6     dhruv     57       52       98          207       69.00
7   chakshu     98       89       95          282       94.00
8    aditya     65       58       70          193       64.33
9     disha     92       85       92          269       89.67
10  yashika     69       55       62          186       62.00

In [90]:
df["city"] = [
    "Delhi", "Delhi", "Noida", "Gurgaon", "Faridabad",
    "Noida", "Delhi", "Gurgaon", "Faridabad", "Noida"
]

In [91]:
df

       name  Maths  science  english  total marks  percentage       city
1   samaira     93       87       73          253       84.33      Delhi
2     sanya     83       86       61          230       76.67      Delhi
3    sanyam     53       78       82          213       71.00      Noida
4   abhinav     58       65       83          206       68.67    Gurgaon
5    soumil     56       80       90          226       75.33  Faridabad
6     dhruv     57       52       98          207       69.00      Noida
7   chakshu     98       89       95          282       94.00      Delhi
8    aditya     65       58       70          193       64.33    Gurgaon
9     disha     92       85       92          269       89.67  Faridabad
10  yashika     69       55       62          186       62.00      Noida

In [92]:
df.groupby("city").city.count()
df.groupby("city").city.unique()

city
Delhi            [Delhi]
Faridabad    [Faridabad]
Gurgaon        [Gurgaon]
Noida            [Noida]
Name: city, dtype: object

In [93]:
df.city.value_counts()

city
Delhi        3
Noida        3
Gurgaon      2
Faridabad    2
Name: count, dtype: int64

In [94]:
df.city.unique()

array(['Delhi', 'Noida', 'Gurgaon', 'Faridabad'], dtype=object)

In [95]:
df['name'] = df.name.str.upper()
df

       name  Maths  science  english  total marks  percentage       city
1   SAMAIRA     93       87       73          253       84.33      Delhi
2     SANYA     83       86       61          230       76.67      Delhi
3    SANYAM     53       78       82          213       71.00      Noida
4   ABHINAV     58       65       83          206       68.67    Gurgaon
5    SOUMIL     56       80       90          226       75.33  Faridabad
6     DHRUV     57       52       98          207       69.00      Noida
7   CHAKSHU     98       89       95          282       94.00      Delhi
8    ADITYA     65       58       70          193       64.33    Gurgaon
9     DISHA     92       85       92          269       89.67  Faridabad
10  YASHIKA     69       55       62          186       62.00      Noida

In [96]:
df["remark"] = df["percentage"].apply(lambda row: "exelent" if (row > 80) else "average")
df

,name,Maths,science,english,total marks,percentage,city,remark
1,SAMAIRA,93,87,73,253,84.33,Delhi,exelent
2,SANYA,83,86,61,230,76.67,Delhi,average
3,SANYAM,53,78,82,213,71.00,Noida,average
4,ABHINAV,58,65,83,206,68.67,Gurgaon,average
5,SOUMIL,56,80,90,226,75.33,Faridabad,average
6,DHRUV,57,52,98,207,69.00,Noida,average
7,CHAKSHU,98,89,95,282,94.00,Delhi,exelent
8,ADITYA,65,58,70,193,64.33,Gurgaon,average
9,DISHA,92,85,92,269,89.67,Faridabad,exelent
10,YASHIKA,69,55,62,186,62.00,Noida,average

In [98]:
df[(df.Maths > 70) & (df.science > 70)]

,name,Maths,science,english,total marks,percentage,city,remark
1,SAMAIRA,93,87,73,253,84.33,Delhi,exelent
2,SANYA,83,86,61,230,76.67,Delhi,average
7,CHAKSHU,98,89,95,282,94.00,Delhi,exelent
9,DISHA,92,85,92,269,89.67,Faridabad,exelent

In [101]:
df[(df.Maths > 90) | (df.english > 90)]

,name,Maths,science,english,total marks,percentage,city,remark
1,SAMAIRA,93,87,73,253,84.33,Delhi,exelent
6,DHRUV,57,52,98,207,69.00,Noida,average
7,CHAKSHU,98,89,95,282,94.00,Delhi,exelent
9,DISHA,92,85,92,269,89.67,Faridabad,exelent