In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
df = pd.DataFrame(np.random.randn(6,4), index=list(range(1,7)), columns=list("ABCD"))
df

          A         B         C         D
1 -0.544718 -0.221172  1.301412  0.819389
2  0.750817  0.097659  0.325031  1.977541
3  2.978330 -0.710418 -0.559102  1.502424
4  1.711158 -0.284093  0.560486  1.203790
5 -0.987319 -0.585558  0.347996 -0.545106
6 -1.640455  0.573460  0.407416 -0.154127

In [12]:
df.head()

          A         B         C         D
1 -0.410477  0.130787  0.432436  0.513169
2 -1.230769 -0.240971  0.391781  1.188612
3  1.065956 -0.507728  0.133253 -0.111364
4 -0.145024 -0.653265  1.521196  1.532770
5  0.531201  0.123193  1.147159 -0.446422

In [14]:
df.tail()

          A         B         C         D
2 -1.230769 -0.240971  0.391781  1.188612
3  1.065956 -0.507728  0.133253 -0.111364
4 -0.145024 -0.653265  1.521196  1.532770
5  0.531201  0.123193  1.147159 -0.446422
6  0.589776 -0.429408  1.793811 -1.852299

In [19]:
df.index

Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [17]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

# SELECTION

In [ ]:
df.A #or df['A']

1   -0.544718
2    0.750817
3    2.978330
4    1.711158
5   -0.987319
6   -1.640455
Name: A, dtype: float64

In [21]:
df[['A', 'B', 'C']]

          A         B         C
1 -0.544718 -0.221172  1.301412
2  0.750817  0.097659  0.325031
3  2.978330 -0.710418 -0.559102
4  1.711158 -0.284093  0.560486
5 -0.987319 -0.585558  0.347996
6 -1.640455  0.573460  0.407416

In [28]:
df[0:3]

          A         B         C         D
1 -0.544718 -0.221172  1.301412  0.819389
2  0.750817  0.097659  0.325031  1.977541
3  2.978330 -0.710418 -0.559102  1.502424

In [23]:
df2 = pd.DataFrame(np.random.randn(6,4), index=list(range(1,7)), columns=list(range(1,5)))
df2

          1         2         3         4
1 -1.665581  1.729807 -0.307716  0.964439
2 -0.228581 -0.377319  0.008924 -0.179291
3 -0.281609  0.914188 -0.008393 -0.302375
4 -0.420335  0.902253 -0.281566  0.417604
5 -2.144630 -1.568017 -1.489429  0.043331
6 -1.441685 -0.687735 -0.780974 -1.124948

In [25]:
df2[0:3]

          1         2         3         4
1 -1.665581  1.729807 -0.307716  0.964439
2 -0.228581 -0.377319  0.008924 -0.179291
3 -0.281609  0.914188 -0.008393 -0.302375

In [ ]:
df.loc[0:3, "A":"C"] #enpoints included in loc

          A         B         C
1 -0.544718 -0.221172  1.301412
2  0.750817  0.097659  0.325031
3  2.978330 -0.710418 -0.559102

In [36]:
df.loc[1, "A"].dtype

dtype('float64')

In [37]:
df.iloc[3]

A    1.711158
B   -0.284093
C    0.560486
D    1.203790
Name: 4, dtype: float64

In [39]:
df.iloc[1:4]

          A         B         C         D
2  0.750817  0.097659  0.325031  1.977541
3  2.978330 -0.710418 -0.559102  1.502424
4  1.711158 -0.284093  0.560486  1.203790

In [40]:
df.iloc[1,2]

0.32503103959977614

## boolean indexing

In [ ]:
df[df.A <= 0]

          A         B         C         D
1 -0.544718 -0.221172  1.301412  0.819389
5 -0.987319 -0.585558  0.347996 -0.545106
6 -1.640455  0.573460  0.407416 -0.154127

In [47]:
df[df.A >= 0]

          A         B         C         D
2  0.750817  0.097659  0.325031  1.977541
3  2.978330 -0.710418 -0.559102  1.502424
4  1.711158 -0.284093  0.560486  1.203790

In [48]:
df[df > 0]

          A         B         C         D
1       NaN       NaN  1.301412  0.819389
2  0.750817  0.097659  0.325031  1.977541
3  2.978330       NaN       NaN  1.502424
4  1.711158       NaN  0.560486  1.203790
5       NaN       NaN  0.347996       NaN
6       NaN  0.573460  0.407416       NaN

In [52]:
df3 = df.copy()
df3['E'] = ["one", "two", "three", "four", "five","six"]
df3

          A         B         C         D      E
1 -0.544718 -0.221172  1.301412  0.819389    one
2  0.750817  0.097659  0.325031  1.977541    two
3  2.978330 -0.710418 -0.559102  1.502424  three
4  1.711158 -0.284093  0.560486  1.203790   four
5 -0.987319 -0.585558  0.347996 -0.545106   five
6 -1.640455  0.573460  0.407416 -0.154127    six

In [58]:
df3[df3.E.isin(["two", "six"])]

          A         B         C         D    E
2  0.750817  0.097659  0.325031  1.977541  two
6 -1.640455  0.573460  0.407416 -0.154127  six

In [66]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index = [1, 2, 3, 4, 5, 6])

In [67]:
df3['f'] = s1
df3

          A         B         C         D      E  f
1 -0.544718 -0.221172  1.301412  0.819389    one  1
2  0.750817  0.097659  0.325031  1.977541    two  2
3  2.978330 -0.710418 -0.559102  1.502424  three  3
4  1.711158 -0.284093  0.560486  1.203790   four  4
5 -0.987319 -0.585558  0.347996 -0.545106   five  5
6 -1.640455  0.573460  0.407416 -0.154127    six  6

# functions

In [81]:
s = pd.Series(np.random.randint(0,7, size=20))
s

0     0
1     2
2     5
3     5
4     5
5     0
6     5
7     0
8     3
9     6
10    6
11    3
12    6
13    1
14    1
15    6
16    6
17    6
18    4
19    4
dtype: int32

In [82]:
s.value_counts().sort_index()

0    3
1    2
2    1
3    2
4    2
5    4
6    6
Name: count, dtype: int64

In [84]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df

        A  B    C         D         E
0     one  A  foo -1.040026  3.283778
1     one  B  foo  1.644180  0.686801
2     two  C  foo  0.573089  0.547664
3   three  A  bar  0.052643  1.281060
4     one  B  bar -0.947679 -0.529366
5     one  C  bar  0.632372  0.152282
6     two  A  foo  0.826522  1.378885
7   three  B  foo -0.722795 -0.342830
8     one  C  foo -0.710346 -0.102775
9     one  A  bar  0.314268 -0.138193
10    two  B  bar  0.004972  0.522831
11  three  C  bar -0.505205 -0.046424

In [ ]:
pd.pivot_table(df, values='D', index=["A", "B"], columns="C")

C             bar       foo
A     B
one   A  0.314268 -1.040026
      B -0.947679  1.644180
      C  0.632372 -0.710346
three A  0.052643       NaN
      B       NaN -0.722795
      C -0.505205       NaN
two   A       NaN  0.826522
      B  0.004972       NaN
      C       NaN  0.573089

In [92]:
pd.pivot_table(df, values=['D', 'E'], index=["A", "B"], columns=["C"])

                D                   E
C             bar       foo       bar       foo
A     B
one   A  0.314268 -1.040026 -0.138193  3.283778
      B -0.947679  1.644180 -0.529366  0.686801
      C  0.632372 -0.710346  0.152282 -0.102775
three A  0.052643       NaN  1.281060       NaN
      B       NaN -0.722795       NaN -0.342830
      C -0.505205       NaN -0.046424       NaN
two   A       NaN  0.826522       NaN  1.378885
      B  0.004972       NaN  0.522831       NaN
      C       NaN  0.573089       NaN  0.547664

In [108]:
rng = pd.date_range("1/1/2012", periods=100, freq="min")
ts = pd.Series(np.random.randint(0,500, len(rng)), index=rng)

ts

2012-01-01 00:00:00    363
2012-01-01 00:01:00     91
2012-01-01 00:02:00    218
2012-01-01 00:03:00    364
2012-01-01 00:04:00     34
                      ...
2012-01-01 01:35:00    432
2012-01-01 01:36:00    105
2012-01-01 01:37:00    360
2012-01-01 01:38:00    489
2012-01-01 01:39:00    248
Freq: min, Length: 100, dtype: int32

In [110]:
ts.resample("15Min").sum()

2012-01-01 00:00:00    3269
2012-01-01 00:15:00    3082
2012-01-01 00:30:00    3974
2012-01-01 00:45:00    4077
2012-01-01 01:00:00    4479
2012-01-01 01:15:00    3858
2012-01-01 01:30:00    3400
Freq: 15min, dtype: int32